openapi: "3.0.0"
info:
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /sauce:
    get:
      parameters:
        - in: query
          name: _for
          schema:
            type: string
          required: true
          example: fries
      responses:
        '200':
          description: Returns the best sauce for the given food.
          content:
            application/json:
              schema:
                type: object
                properties:
                  deliciousSauce:
                    required: true
                    type: string
              example:
                deliciousSauce: ketchup
